### ISSUE TITLE
Low value rewards

### ISSUE THREAD

**Issue by Yelnats321** [brandonm4/BannerlordMods#1]
I'm not sure if this is a fault of the mod or otherwise, but some tournament rewards are improperly valued. I've had such issues with pernach_mace_t3 and knights_fall_mace_t3, these items are both claimed to have a value of 7k+ but when received had a value of 130 and 70 respectively. Are these rewards part of the vanilla rewards? I am play on e1.0.4.

**Comment by brandonm4** [comment]
Yes percach and knights fall are both standard rewards.  The list provided by default in the BMTournamentPrizes file are straight from the game code of normal prizes.

**Comment by Yelnats321** [comment]
Do you have any idea how the game calculates the total reward value? It seems to get more and more inaccurate as the game goes on.

**Comment by brandonm4** [comment]
The vanilla process is quite simple.  There's a hardcoded list of items, it randomly picks one.

For the amount of money you win by betting - it's also simple in vanilla - it takes all the levels of your team vs all the levels of the opposing teams and gets the ratio.  Then clamps that to be between 1.0 and 2.0.

If you use mine and enable the odds calculations - it takes into account not just their level, but skills, equipment, and health, which I think provides a better ratio.

**Comment by Yelnats321** [comment]
I realize now that the last row value is your total wealth.
