### ISSUE TITLE
After updating to use with e1.2 stable. Unable to save my game random time after doing a tournament.

### ISSUE THREAD

**Issue by NicTanghe** [brandonm4/BannerlordMods#3]
Checked on the forom for why i'm having this issue.
It's 100% not an antivirus causing this or a ful harddrive.
encountered a forumpost saying it happend to him to after updating ur mod.
not 100% sure it's your mod but i'm quite sure.
he says it corrupts something in the savfile so disabeling the mod whouldn't fix it.
here's the post i'm referring to.

https://forums.taleworlds.com/index.php?threads/game-is-unable-to-save-config-savegame-files-in-documents-mount-and-blade-ii-bannerlord.404978/page-2

**Comment by brandonm4** [comment]
Try version 1.6.3.hf2 - I've been playing all day on 1.6.3.hf1 but some people were still having issues.  Both hf1 and hf2 should fix your save issues if they are caused by this mod.

**Comment by NicTanghe** [comment]
i'm thinking its a combination of allot of things i deinstalled ur mod and stil have it sometimes but not asoften. seems multiple mods are having this same issue.
u blocked me from downloading on nexus i'm drunkenpanda andd ws raging becouse i had to restart 2ce in 1 day.

**Comment by brandonm4** [comment]
I’ll unblock you when I get back to my pc.  I don’t mind trying to help people, I just don’t care for drama and hysterics.  I know it’s frustrating when I game doesn’t work.

Sent from my iPad

On Apr 26, 2020, at 1:21 PM, NicTanghe <notifications@github.com> wrote:

﻿

i'm thinking its a combination of allot of things i deinstalled ur mod and stil have it sometimes but not asoften. seems multiple mods are having this same issue.
u blocked me from downloading on nexus i'm drunkenpanda andd ws raging becouse i had to restart 2ce in 1 day.
